name: My first workflow

on: workflow_dispatch

jobs:
  my-amazing-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The amazing job has started"
      - run: echo "This was triggered by a ${{ github.event_name }} event."
      - run: echo "Runner OS ${{ runner.os }}"
      - run: echo "Repository ${{ github.repository }}"
      - run: echo "Branch Name ${{ github.ref }}"
      - run: echo "The amazing job is complete"
  my-amazing-checkout-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Cloning ${{ github.repository }} to runner..."
      - name: Checkout repo
        uses: actions/checkout@v4.1.1
      - run: echo "The repo has been cloned and is ready for... well... anything!"
      - name: List files in repo
        run: |
          ls -lah ${{ github.workspace }};
          echo "Contents of kapitel_1.txt";
          cat kapitel_1.txt
        
